# Generated by Django 4.2.4 on 2023-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacy",
            name="drugs",
            field=models.ManyToManyField(to="demo.drug"),
        ),
    ]
