# Generated by Django 4.2.4 on 2023-09-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_pharmacy_drugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="open_fda",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="demo.openfdadrug",
                verbose_name="OpenFDA label",
            ),
        ),
    ]
