# Generated by Django 4.2.4 on 2023-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_pharmacy_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="drugs",
            field=models.ManyToManyField(null=True, to="demo.drug"),
        ),
    ]
