# Generated by Django 4.2.4 on 2023-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0005_alter_pharmacy_drugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="drugs",
            field=models.ManyToManyField(blank=True, to="demo.drug"),
        ),
    ]
