# Generated by Django 4.2.4 on 2023-09-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0006_alter_pharmacy_drugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="logo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
