# Generated by Django 4.2.4 on 2023-10-02 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("demo", "0008_alter_pharmacy_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_theme",
                    models.CharField(
                        blank=True,
                        choices=[("dark", "dark"), ("light", "light")],
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demo.userpreference",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="demo.manager"
            ),
        ),
    ]
