# Generated by Django 4.2.4 on 2023-10-02 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0010_remove_manager_id_alter_manager_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="user_preference",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demo.userpreference",
            ),
        ),
    ]
