# Generated by Django 4.2.4 on 2023-10-02 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0012_alter_manager_user_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="user_preference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demo.userpreference",
            ),
        ),
    ]
