# Generated by Django 4.2.4 on 2023-10-14 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0013_alter_manager_user_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="user_preference",
        ),
    ]
