# Generated by Django 4.2.4 on 2023-10-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0014_remove_manager_user_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreference",
            name="id",
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="demo.manager",
            ),
            preserve_default=False,
        ),
    ]
