# Generated by Django 4.2.4 on 2023-11-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0015_remove_userpreference_id_userpreference_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Pharmacy name"
            ),
        ),
    ]
