# Generated by Django 4.2.4 on 2023-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0016_alter_pharmacy_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="preferred_theme",
            field=models.CharField(
                blank=True,
                choices=[("dark", "dark"), ("light", "light")],
                max_length=8,
                null=True,
            ),
        ),
    ]
